### ISSUE TITLE
Email Feld eingaben werden nicht im PDF angezeigt?

### ISSUE THREAD

**Issue by DjCrays** [HerrLevin/selbstauskunft#3]
Hey, Wenn ich in dem Email Feld eine Emailadresse angebe zB h@h oder auch h@example.de wird diese nicht im PDF in der Adressezeile angezeigt. Da ja auch keine Email mit dem PDF an mich dann rausgeht, verstehe ich nicht ganz genau den Grund für das Email Feld dann.

**Comment by HerrLevin** [comment]
Das ist noch ein Überbleibsel aus dem ursprünglichen Template. Vorerst mal auskommentiert, damit es nicht stört.
